apiVersion: v1
kind: Secret
metadata:
  name: loki-grafana
  namespace: loki
  labels: 
    app.kubernetes.io/instance: loki
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 8.3.5
    helm.sh/chart: grafana-6.43.5
  annotations:  
    meta.helm.sh/release-name: loki
    meta.helm.sh/release-namespace: loki
type: Opaque

data:
  admin-user: YWRtaW4=
  admin-password: YWRtaW4=